language: sql
# blacklist
branches:
  except:
    - master

env:
  - DB=db2
  - DB=postgres

before_install:
  # Compiles the sources.
  - ant compile

  - pwd
  - df -h

  # DB2
  # Install the required libraries
  - sudo apt-get update -qq
  - sh -c "if [ '$DB' = 'db2' ]; then sudo apt-get -y install ksh curl aria2 numactl ; fi"
  - sh -c "if [ '$DB' = 'db2' ]; then sudo apt-get -y install rpm binutils libaio1 lib32stdc++6 ; fi"
  - sh -c "if [ '$DB' = 'db2' ]; then sudo apt-get install -qq libpam-ldap:i386 ; fi"
  - sh -c "if [ '$DB' = 'db2' ]; then sudo ln -s /lib/i386-linux-gnu/libpam.so.0 /lib/libpam.so.0 ; fi"
    # Retrieves and extracts the DB2 binaries
  - cd /tmp
  - sh -c "if [ '$DB' = 'db2' ]; then curl --url https://raw.githubusercontent.com/wiki/ECI-SGBD/BenchmarkSQL-4/DB2-Download-link.md -s > link ; cat link | tail -1 > link2 ; cat link2 ; fi"
  - sh -c "if [ '$DB' = 'db2' ]; then aria2c -x 16 $(cat link2) ; fi"
  - sh -c "if [ '$DB' = 'db2' ]; then ls -1 v*.tar.gz ; tar zvxf $(ls -1 v*.tar.gz) ; fi"
  # Checks the prerequisites
  - sh -c "if [ '$DB' = 'db2' ]; then server_t/db2prereqcheck -i -l ; fi"
  # Install DB2 and creates an instance (Response file)
  - sh -c "if [ '$DB' = 'db2' ]; then sudo server_t/db2setup -r ${TRAVIS_BUILD_DIR}/run/db2/db2expc.rsp || cat /tmp/db2setup.log ; fi"
  - sh -c "if [ '$DB' = 'db2' ]; then echo \"db2admin\\\ndb2admin\" | sudo passwd db2inst1 ; fi"
  # Creates the database
  - sh -c "if [ '$DB' = 'db2' ]; then sudo su - db2inst1 -c \"db2 create db bmarkdb\" ; fi"
  - sh -c "if [ '$DB' = 'db2' ]; then sudo su - db2inst1 -c \"db2 connect to bmarkdb ; db2 grant dbadm on database to user ${USER}\" ; fi"

  # Postgres
  - sh -c "if [ '$DB' = 'postgres' ]; then sudo -u postgres psql -c \"create user benchmarksql with superuser password 'password'\" ; fi"
  - sh -c "if [ '$DB' = 'postgres' ]; then sudo -u postgres psql -c \"grant all privileges on database postgres to benchmarksql\" ; fi"

  - df -h
  - df -ih

install:
  - cd ${TRAVIS_BUILD_DIR} ; ant dist

  # DB2
  # Modifies the scripts
  - cd ${TRAVIS_BUILD_DIR}/run
  - sh -c "if [ '$DB' = 'db2' ]; then sed -i 's/^myCP=\"\.\./myCP=\"\/opt\/ibm\/db2\/Vx\/java\/db2jcc4\.jar:\.\./g' runSQL ; fi"
  - sh -c "if [ '$DB' = 'db2' ]; then sed -i 's/-cp \.:/-cp \.:\/opt\/ibm\/db2\/Vx\/java\/db2jcc4\.jar:/g' runBenchmark ; fi"
  - sh -c "if [ '$DB' = 'db2' ]; then sed -i 's/-cp \.:/-cp \.:\/opt\/ibm\/db2\/Vx\/java\/db2jcc4\.jar:/g' runLoader ; fi"
  - cat run*.sh
  - chmod +x run*.sh

  - sh -c "if [ '$DB' = 'db2' ]; then cd ${TRAVIS_BUILD_DIR}/run/db2 ; ./runSQL db2.properties sqlTableCreates.sql ; fi"

  # Postgres
  - sh -c "if [ '$DB' = 'postgres' ]; then cd ${TRAVIS_BUILD_DIR}/run/postgres ; ./runSQL postgres.properties sqlTableCreates.sql ; fi"
  - df -h

script:
  - sh -c "if [ '$DB' = 'db2' ]; then ./runLoader db2.properties numWarehouses 1 ; fi"
  - sh -c "if [ '$DB' = 'db2' ]; then ./runSQL db2.properties sqlIndexCreates.sql ; fi"
  - sh -c "if [ '$DB' = 'db2' ]; then ./runBenchmark db2.properties ; fi"

  - sh -c "if [ '$DB' = 'postgres' ]; then ./runLoader postgres.properties numWarehouses 1 ; fi"
  - sh -c "if [ '$DB' = 'postgres' ]; then ./runSQL postgres.properties sqlIndexCreates.sql ; fi"
  - sh -c "if [ '$DB' = 'postgres' ]; then ./runBenchmark postgres.properties; fi"

after_script:
  - df -h
  - df -ih
  - cat log/BenchmarkSQLError.log
  - cat log/benchmarksql.log

