#!/bin/bash

# Executes the given SQL with the given database properties.
#
# 1) Database properties file.
# 2) SQL script file.
#
# Author: Denis Lussier.
# Author: Andres Gomez.

MY_CLASSPATH="../target/benchmarksql*.jar:../lib/db2jcc4.jar"

MY_PROPERTIES="-Dprop=${1} -DcommandFile=${2}"

java -cp .:${MY_CLASSPATH} ${MY_PROPERTIES} com.github.benchmarksql.ExecJDBC
