#!/bin/bash

# 1) Database properties file.
#
# Author: AmitDutta.

PROPERTIES=${1}

LOG="${PROPERTIES}_$(date "+%m-%d-%Y_%H-%M-%S").log"
touch ${LOG}
for ((i=1; i<=$2; ++i)) ; do
	START_TIME=$(date +%s%N)
	
	./runSQL ${PROPERTIES} sqlTableCreates.sql
	./loadData.sh ${PROPERTIES} numWarehouses 10
	./runSQL ${PROPERTIES} sqlIndexCreates.sql
	./runBenchmark ${PROPERTIES}
	./runSQL.sh ${PROPERTIES} sqlTableDrops
	
	END_TIME=$(date +%s%N)
	DIFF=$(( ${END_TIME} - ${START_TIME} ))
	echo "Iteration: ${i}, Time: ${DIFF} nanoseconds" >> ${LOG}
done
