package com.github.benchmarksql.jtpcc.pojo;

import java.io.Serializable;

public class Warehouse implements Serializable {

	/**
	 * Generated Id.
	 */
	private static final long serialVersionUID = 933859184143183210L;

	private String w_city;

	/**
	 * Id of the warehouse. Primary key.
	 */
	private int w_id;

	private String w_name;

	private String w_state;

	private String w_street_1;

	private String w_street_2;

	private float w_tax;

	private float w_ytd;

	private String w_zip;

	/**
	 * Default constructor.
	 */
	public Warehouse() {
		// Empty
	}

	/**
	 * Gets the city of the warehouse. Random string between 10 and 20 characters.
	 * 
	 * @return City of the warehouse.
	 */
	public String getW_city() {
		return w_city;
	}

	/**
	 * Gets the id of the warehouse.
	 * 
	 * @return Warehouse id.
	 */
	public int getW_id() {
		return w_id;
	}

	/**
	 * Gets the name of the warehouse. Random string between 6 and 10 characters.
	 * 
	 * @return Name of the warehouse.
	 */
	public String getW_name() {
		return w_name;
	}

	/**
	 * Gets the state of the warehouse. A two letters code.
	 * 
	 * @return State of the warehouse.
	 */
	public String getW_state() {
		return w_state;
	}

	/**
	 * Gets the street of the warehouse. A random string between 10 and 20
	 * characters.
	 * 
	 * @return Street of the warehouse.
	 */
	public String getW_street_1() {
		return w_street_1;
	}

	/**
	 * Gets the complements of the warehouse address. A random string between 10 and
	 * 20 characters.
	 * 
	 * @return Address complement of the warehouse.
	 */
	public String getW_street_2() {
		return w_street_2;
	}

	/**
	 * Value of the tax. A random value between 0.0000 and 0.2000.
	 * 
	 * @return Value of the tax.
	 */
	public float getW_tax() {
		return w_tax;
	}

	/**
	 * Gets the year to date value. Fixed value of 300 000.
	 * 
	 * @return Year to date value.
	 */
	public float getW_ytd() {
		return w_ytd;
	}

	/**
	 * Gets the zip of the address. Generated by clause 4.3.2.7.
	 * 
	 * @return Zip of the address.
	 */
	public String getW_zip() {
		return w_zip;
	}

	/**
	 * Sets the city of the warehouse. Random string between 10 and 20 characters.
	 * 
	 * @param w_city City of the warehouse.
	 */
	public void setW_city(String w_city) {
		this.w_city = w_city;
	}

	/**
	 * Sets the id of the warehouse.
	 * 
	 * @param w_idWarehouse id.
	 */
	public void setW_id(int w_id) {
		this.w_id = w_id;
	}

	/**
	 * Sets the name of the warehouse. Random string between 6 and 10 characters.
	 * 
	 * @param w_name Name of the warehouse.
	 */
	public void setW_name(String w_name) {
		this.w_name = w_name;
	}

	/**
	 * Sets the state of the warehouse. A two letters code.
	 * 
	 * @param w_state State of the warehouse.
	 */
	public void setW_state(String w_state) {
		this.w_state = w_state;
	}

	/**
	 * Sets the street of the warehouse. A random string between 10 and 20
	 * characters.
	 * 
	 * @param w_street_1 Street of the warehouse.
	 */
	public void setW_street_1(String w_street_1) {
		this.w_street_1 = w_street_1;
	}

	/**
	 * Sets the complements of the warehouse address. A random string between 10 and
	 * 20 characters.
	 * 
	 * @param w_street_2 Address complement of the warehouse.
	 */
	public void setW_street_2(String w_street_2) {
		this.w_street_2 = w_street_2;
	}

	/**
	 * Value of the tax. A random value between 0.0000 and 0.2000.
	 * 
	 * @param w_tax Value of the tax.
	 */
	public void setW_tax(float w_tax) {
		this.w_tax = w_tax;
	}

	/**
	 * Sets the year to date value. Fixed value of 300 000.
	 * 
	 * @param w_ytd Year to date value.
	 */
	public void setW_ytd(float w_ytd) {
		this.w_ytd = w_ytd;
	}

	/**
	 * Sets the zip of the address. Generated by clause 4.3.2.7.
	 * 
	 * @param w_zip Zip of the address.
	 */
	public void setW_zip(String w_zip) {
		this.w_zip = w_zip;
	}

	/**
	 * Describes the warehouse.
	 */
	@Override
	public String toString() {
		StringBuffer ret = new StringBuffer("");
		ret.append("\n***************** Warehouse ********************");
		ret.append("\n*       w_id = " + w_id);
		ret.append("\n*      w_ytd = " + w_ytd);
		ret.append("\n*      w_tax = " + w_tax);
		ret.append("\n*     w_name = " + w_name);
		ret.append("\n* w_street_1 = " + w_street_1);
		ret.append("\n* w_street_2 = " + w_street_2);
		ret.append("\n*     w_city = " + w_city);
		ret.append("\n*    w_state = " + w_state);
		ret.append("\n*      w_zip = " + w_zip);
		ret.append("\n**********************************************");
		return ret.toString();
	}

}
